# Generated by Django 3.2.18 on 2023-03-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lesson_time',
            field=models.TimeField(),
        ),
    ]
