# Generated by Django 3.2.18 on 2023-03-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_lesson_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='height',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='weight',
        ),
        migrations.AddField(
            model_name='booking',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_requests',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
