# Generated by Django 3.2.18 on 2023-03-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
