# Generated by Django 3.2.18 on 2023-03-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_customer_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
